import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

// styles
import styles from '../styles/Home.module.css'
import login from '../styles/login.module.css'

// components

// assets
import rty_logo from '../public/logo/rentify-logo.svg'

export default function Home() {
  return (
    <div className={styles.main_container}>
      <Head>
        <title>Rentify | ADMIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main_content}>
        <div className={login.main_login_content}>
          <div className={login.main_login_graphic_container}>
            <Image src={rty_logo} alt='Rentify Logo' />
          </div>


          <div className={login.main_login_form_container}>
            <h3 className={login.main_login_form_head}>Admin Login</h3>

            <form className={login.login_form}>
              <div className={login.login_form_inpgroup}>
                <p className={login.login_form_label}>Admin ID</p>
                <input className={login.login_form_inpfield}
                type="text" id="adminUsername"
                name="adminUsername"
                />
              </div>

              <div className={login.login_form_inpgroup}>
                <p className={login.login_form_label}>Password</p>
                <input className={login.login_form_inpfield}
                type="password" id="adminPassword"
                name="adminPassword"
                />
              </div>

              <div className={login.login_form_submitgroup}>
                <button className={login.login_form_submitbtn} type='submit'>Login</button>
              </div>
            </form>
          </div>

          <div>
            <Link href="/dashboard">Dashboard</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
