import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

// styles
import styles from '../../styles/Home.module.css'
import dashboard from '../../styles/dashboard/dashboard.module.css'

// components
import MainHeader from '../../components/header/MainHeader'
import MainSidebar from '../../components/sidebar/MainSidebar'

// assets
import roomResIcon from '../../public/svg/room_res_icon.svg'
import equipResIcon from '../../public/svg/equip_res_icon.svg'

export default function Dashboard() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Rentify | ADMIN DASHBOARD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.main_content}>
                <MainHeader />

                <div className={styles.main_layout}>
                    <MainSidebar />
                    <div className={styles.main_layout_content}>
                        <div className={dashboard.main_dashboard_herobanner}>
                            <h1>Welcome Admin!</h1>
                            <h3>January 20, 2024 | 9:01am</h3>
                        </div>

                        <div className={dashboard.main_dashboard_stats_container}>
                            <div className={dashboard.main_dashboard_stats_div}>
                                <div className={dashboard.main_dashboard_stats_graphic}>
                                    <Image src={roomResIcon} alt='Room Icon' height={60} width={60} />
                                </div>

                                <div className={dashboard.main_dashboard_stats_infodiv}>
                                    <p className={dashboard.main_dashboard_stats_head}>Room Reservations</p>
                                    <h1>{0}</h1>
                                </div>
                            </div>

                            <div className={dashboard.main_dashboard_stats_div}>
                                <div className={dashboard.main_dashboard_stats_graphic}>
                                    <Image src={equipResIcon} alt='Equipment Icon' height={60} width={60} />
                                </div>

                                <div className={dashboard.main_dashboard_stats_infodiv}>
                                    <p className={dashboard.main_dashboard_stats_head}>Equipment Reservations</p>
                                    <h1>{0}</h1>
                                </div>
                            </div>

                            <div className={dashboard.main_dashboard_stats_div}>
                                <div className={dashboard.main_dashboard_stats_graphic}>
                                    <Image src={roomResIcon} alt='Room Icon' height={60} width={60} />
                                </div>

                                <div className={dashboard.main_dashboard_stats_infodiv}>
                                    <p className={dashboard.main_dashboard_stats_head}>Available Rooms</p>
                                    <h1>{0}</h1>
                                </div>
                            </div>

                            <div className={dashboard.main_dashboard_stats_div}>
                                <div className={dashboard.main_dashboard_stats_graphic}>
                                    <Image src={equipResIcon} alt='Equipment Icon' height={60} width={60} />
                                </div>

                                <div className={dashboard.main_dashboard_stats_infodiv}>
                                    <p className={dashboard.main_dashboard_stats_head}>Available Equipments</p>
                                    <h1>{0}</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}